export const GET_VENDOR_ANALYTICS_REQUEST = "GET_VENDOR_ANALYTICS_REQUEST";
export const GET_VENDOR_ANALYTICS_SUCCESS = "GET_VENDOR_ANALYTICS_SUCCESS";
export const GET_VENDOR_ANALYTICS_FAIL = "GET_VENDOR_ANALYTICS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
