export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAIL = "GET_NOTIFICATIONS_FAIL";

export const MARK_AS_READ_REQUEST = "MARK_AS_READ_REQUEST";
export const MARK_AS_READ_SUCCESS = "MARK_AS_READ_SUCCESS";
export const MARK_AS_READ_FAIL = "MARK_AS_READ_FAIL";
export const MARK_AS_READ_RESET = "MARK_AS_READ_RESET";

export const MARK_ALL_READ_REQUEST = "MARK_ALL_READ_REQUEST";
export const MARK_ALL_READ_SUCCESS = "MARK_ALL_READ_SUCCESS";
export const MARK_ALL_READ_FAIL = "MARK_ALL_READ_FAIL";
export const MARK_ALL_READ_RESET = "MARK_ALL_READ_RESET";

export const CLEAR_ALL_NOTIFICATIONS_REQUEST = "CLEAR_ALL_NOTIFICATIONS_REQUEST";
export const CLEAR_ALL_NOTIFICATIONS_SUCCESS = "CLEAR_ALL_NOTIFICATIONS_SUCCESS";
export const CLEAR_ALL_NOTIFICATIONS_FAIL = "CLEAR_ALL_NOTIFICATIONS_FAIL";
export const CLEAR_ALL_NOTIFICATIONS_RESET = "CLEAR_ALL_NOTIFICATIONS_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
