export const GET_VENDOR_ANALYTICS_REQUEST = "GET_VENDOR_ANALYTICS_REQUEST";
export const GET_VENDOR_ANALYTICS_SUCCESS = "GET_VENDOR_ANALYTICS_SUCCESS";
export const GET_VENDOR_ANALYTICS_FAIL = "GET_VENDOR_ANALYTICS_FAIL";

export const GET_ADMIN_ANALYTICS_REQUEST = "GET_ADMIN_ANALYTICS_REQUEST";
export const GET_ADMIN_ANALYTICS_SUCCESS = "GET_ADMIN_ANALYTICS_SUCCESS";
export const GET_ADMIN_ANALYTICS_FAIL = "GET_ADMIN_ANALYTICS_FAIL";

export const GET_ADMIN_REPORTS_REQUEST = "GET_ADMIN_REPORTS_REQUEST";
export const GET_ADMIN_REPORTS_SUCCESS = "GET_ADMIN_REPORTS_SUCCESS";
export const GET_ADMIN_REPORTS_FAIL = "GET_ADMIN_REPORTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
