export const ALL_PAYMENTS_REQUEST = "ALL_PAYMENTS_REQUEST";
export const ALL_PAYMENTS_SUCCESS = "ALL_PAYMENTS_SUCCESS";
export const ALL_PAYMENTS_FAIL = "ALL_PAYMENTS_FAIL";

export const VENDOR_PAYMENTS_REQUEST = "VENDOR_PAYMENTS_REQUEST";
export const VENDOR_PAYMENTS_SUCCESS = "VENDOR_PAYMENTS_SUCCESS";
export const VENDOR_PAYMENTS_FAIL = "VENDOR_PAYMENTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
